// a0 = 0
// a1 = a2 + a3
// a5 = a6 / (a3 - a4)

?start: substitution*

substitution: VARNAME "=" sum -> assign_var

?sum: product
    | sum "+" product   -> add
    | sum "-" product   -> sub

?product: atom
    | product "*" atom  -> mul
    | product "/" atom  -> div

?atom: NUMBER           -> number
        | atom "**" atom  -> pow
        | "-" atom         -> neg
        | VARNAME             -> var
        | "(" sum ")"


VARNAME : LETTER+ DIGIT*

%import common.NEWLINE
%import common.LETTER
%import common.DIGIT
%import common.NUMBER
%import common.WS_INLINE

%ignore WS_INLINE
%ignore NEWLINE